
name: 'Litmus Test'
description: 'Run Litmus Benchmarking Test'
inputs:
  run_name:  # id of input
    description: 'unique name for the run'
    required: true
    type: string
    default: "${{ github.workflow_ref }}/${{ github.run_id }}/${{ github.run_attempt }}"
  litmus_key:  # id of input
    description: 'key for litmus aa'
    required: true
    type: string
  endpoint:  # id of input
    description: 'model endpoint to test'
    required: true
    type: string
  cookbpooks:  # id of input
    description: 'cookcbooks to run against the model endpoint'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Send Run Request
      uses: cssnr/web-request-action@master
      with:
          url: https://litmus.dev.aiguardian.gov.sg/api/v1/benchmarks
          method: POST
          data: |
            {
              "run_name": "${{ inputs.run_name }}",
              "description": "",
              "endpoints": [
                ${{ inputs.endpoint }}
              ],
              "inputs": [
                ${{ inputs.cookbpooks }}
              ],
              "num_of_prompts": 1,
              "random_seed": 0,
              "system_prompt": "",
              "runner_processing_module": ""
            }
          headers: '{"X-API-Key": ${{ inputs.litmus_key }}}'
          params: '{"type": "cookbook"}'
          insecure: false
